### ISSUE TITLE
Error when installing corenlp

### ISSUE THREAD

**Issue by caiyishu** [MS20190155/Measuring-Corporate-Culture-Using-Machine-Learning#3]
I followed your instructions to install the corenlp in Win10. However, when I run "python -m culture.preprocess" to check if well set up, there returned:

  File "C:\Python39\lib\site-packages\stanfordnlp\server\client.py", line 311, in _request
    self.ensure_alive()
  File "C:\Python39\lib\site-packages\stanfordnlp\server\client.py", line 137, in ensure_alive
    raise PermanentlyFailedException("Timed out waiting for service to come alive.")
stanfordnlp.server.client.PermanentlyFailedException: Timed out waiting for service to come alive.

Could you give me some suggestions to handle this problem?

**Comment by caiyishu** [comment]
This situation only occurred when I set the environment variable to the corenlp, while the program worked with modifying the global_options.py.

**Comment by maifeng** [comment]
Setting the environment variable depends on your OS. Perhaps check StackOverflow. Closed.

**Comment by caiyishu** [comment]
> Setting the environment variable depends on your OS. Perhaps check StackOverflow. Closed.

Thank you! The problem was settled by your solution.
